### ISSUE TITLE
Suppoert "reduce-motion" media query

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#190]
The `<MarigoldProvider>` should enforce good a11y and support the `reduce-motion` media query. Here is a good article about it from CSS-Tricks: 

https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/

Gist: The following CSS should be automatically added by our provider to global CSS.

```css
@media screen and
  (prefers-reduced-motion: reduce), 
  (update: slow) {
  * {
    animation-duration: 0.001ms !important;
    animation-iteration-count: 1 !important; /* Hat tip Nick/cssremedy (https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/#comment-1700170) */
    transition-duration: 0.001ms !important;
  }
}
```
